export About from './About/About';
export App from './App/App';
export Vision from './Vision/Vision';
export Refund from './Refund/Refund';
export Home from './Home/Home';
export EventDescription from './EventDescription/EventDescription';
export BookEvent from './BookEvent/BookEvent';
export ThankYouPage from './ThankYouPage/ThankYouPage';
export Terms from './Terms/Terms';
export PreHome from './PreHome/PreHome';
export Privacy from './Privacy/Privacy';
export NotFound from './NotFound/NotFound';
// export Register from './Register/Register';
// export Survey from './Survey/Survey';
// export Widgets from './Widgets/Widgets';
